---
# tasks file for blank-role

- name: Install Samba
  yum:
    name: samba
    state: latest
    
- name: Install Samba Common Tools
  yum:
    name: samba-common-tools
    state: latest

- name: Copy /etc/krb5.conf
  template:
    src: file/etc/krb5.conf
    dest: /etc/krb5.conf

- name: Copy /etc/samba/smb.conf
  template:
    src: file/etc/smb.conf
    dest: /etc/samba/smb.conf

- name: Copy /etc/samba/user.map
  template:
    src: file/etc/samba/user.map
    dest: /etc/samba/user.map